# PCPC Frontend Deployment Pipeline
# Azure DevOps pipeline for building and deploying Svelte frontend to Azure Static Web Apps

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app/frontend/**
      - pipelines/frontend-pipeline.yml
      - pipelines/templates/frontend-*.yml
      - pipelines/scripts/verify-frontend-deployment.sh

pr:
  branches:
    include:
      - main
  paths:
    include:
      - app/frontend/**

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: pcpc-frontend-dev
  - name: nodeVersion
    value: "22.x"
  - name: workingDirectory
    value: "$(System.DefaultWorkingDirectory)/app/frontend"
  - name: staticWebAppName
    value: "pcpc-swa-dev"

stages:
  # Stage 1: Build and Test Frontend
  - stage: Build
    displayName: "Build & Test Frontend"
    jobs:
      - template: templates/frontend-build.yml
        parameters:
          nodeVersion: $(nodeVersion)
          workingDirectory: $(workingDirectory)

  # Stage 2: Deploy to Azure Static Web Apps
  - stage: Deploy
    displayName: "Deploy to Static Web App"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: templates/frontend-deploy.yml
        parameters:
          environment: "dev"
          staticWebAppName: $(staticWebAppName)
          serviceConnection: "pcpc-dev-static-web-app"
