services:
  devcontainer:
    image: maberdevcontainerregistry-ccedhvhwfndwetdp.azurecr.io/pcpc-devcontainer:latest
    pull_policy: always #Always pull fresh image
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    environment:
      - AzureWebJobsStorage=${AzureWebJobsStorage}
      - COSMOS_DB_CONNECTION_STRING=${COSMOS_DB_CONNECTION_STRING}
      - BLOB_STORAGE_CONNECTION_STRING=${BLOB_STORAGE_CONNECTION_STRING}
    networks:
      - devcontainer-network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "4"
        reservations:
          memory: 2G
          cpus: "2"
    restart: unless-stopped
    # depends_on:
    #   azurite:
    #     condition: service_healthy
    #   cosmosdb-emulator:
    #     condition: service_healthy

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose --skipApiVersionCheck
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "apk add --no-cache curl >/dev/null 2>&1 || true; curl -s -o /dev/null http://localhost:10000/devstoreaccount1/",
        ]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      - devcontainer-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
        reservations:
          memory: 512M
          cpus: "0.5"

  cosmosdb-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    platform: linux/amd64
    ports:
      - "8081:8081"
      - "10250-10255:10250-10255"
    volumes:
      - cosmos-data:/tmp/cosmos/appdata
    environment:
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-lc",
          "curl -k -s https://localhost:8081/_explorer/emulator.pem >/dev/null",
        ]
      interval: 5s
      timeout: 3s
      retries: 24
    networks:
      - devcontainer-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: "4"
        reservations:
          memory: 4G
          cpus: "2"
    shm_size: 2G

volumes:
  azurite-data:
  cosmos-data:

networks:
  devcontainer-network:
    driver: bridge
